import Foundation

enum CancelExcuses {
    static let funnyExcuses = [
        "My dog looked sad. I couldn't leave him.",
        "I forgot I'm socially drained this week.",
        "I accidentally made other plans… with my couch.",
        "Mercury is in retrograde and I'm not okay.",
        "I just realized I'm broke.",
        "I thought this was next week.",
        "I sneezed weird and now I think I'm dying.",
        "I got stuck in a deep scroll and lost all sense of time.",
        "I shaved one leg and gave up. Not going out like this.",
        "My cat is being weird. I need to supervise.",
        "I saw a cloud that looked like a bad omen.",
        "I don't feel cute enough today.",
        "I started watching a show and now I'm emotionally unavailable.",
        "I mentally committed to staying in. Can't betray myself.",
        "I have a mysterious stomach situation.",
        "My jeans don't fit. That's the end of it.",
        "I ran out of dry shampoo and confidence.",
        "I touched grass and instantly needed to nap.",
        "I just remembered I hate people.",
        "My therapist said I should rest (I don't have one, but still).",
        "I felt a vibe shift and it told me no.",
        "My phone is at 12% and so is my will to socialize.",
        "I saw a TikTok that told me to protect my peace.",
        "I said yes out of guilt. I'm cancelling out of self-love.",
        "I'm ghosting, but politely.",
        "I got too comfortable. Physically and emotionally.",
        "I'm already in pajamas. No turning back.",
        "I forgot how to human today.",
        "I just don't want to. And that's valid.",
        "I think I saw my ex and now I need to hide.",
        "I remembered I'm an introvert.",
        "I made plans with my bed.",
        "I'm overwhelmed by existing.",
        "My social battery is below 5%.",
        "I got distracted by my own thoughts.",
        "I'm in a committed relationship with my blanket.",
        "My inner child needs me to cancel.",
        "I tripped on vibes and can't recover.",
        "My chakras are misaligned.",
        "I'm detoxing from plans.",
        "My horoscope said 'avoid chaos' and here we are.",
        "I forgot I hate traffic.",
        "I emotionally overcommitted.",
        "I double-booked with my own laziness.",
        "I ran out of small talk.",
        "I'm going through a personal...something.",
        "I'm tired from pretending to be fine.",
        "I started a deep clean and can't stop now.",
        "I made soup and that's my whole night now.",
        "I looked at my calendar and got dizzy.",
        "I need to recharge in airplane mode.",
        "I'm allergic to plans today.",
        "I'm on strike from productivity.",
        "I sneezed and that was my last energy.",
        "My WiFi works, but I don't.",
        "I rewatched one sad scene and now I'm emotionally unavailable.",
        "I remembered this is not my vibe.",
        "I caught a case of 'no thanks.'",
        "I had one minor inconvenience and now I need a week off.",
        "My plants need emotional support.",
        "I got caught in a feelings spiral.",
        "I just... can't.",
        "I saw the weather and I'm not built for that.",
        "I forgot how to socialize.",
        "I just want to be horizontal.",
        "I'm on a date with doomscrolling.",
        "I'm letting my silence speak for me today.",
        "I was brave when I made plans. That bravery is gone.",
        "I overslept emotionally.",
        "I accidentally sat down.",
        "My brain said 'abort mission.'",
        "I'm practicing saying no.",
        "I have a date with my inner peace.",
        "My future self said 'cancel that.'",
        "I'm saving my energy for something I'll also cancel.",
        "I have a sudden urge to overthink in solitude.",
        "My heart's not in it. My sweatpants are.",
        "I'm haunted by past small talk.",
        "I have a fear of commitment... to this plan.",
        "I reached my weekly quota of extroverting.",
        "I need to emotionally hibernate.",
        "I canceled mentally already, this is just logistics.",
        "I need a self-care day (which means avoiding everyone).",
        "I'm rehearsing for a role as someone who doesn't show up.",
        "The simulation glitched. I'm out.",
        "I'm a main character. Today is my sad montage.",
        "I saw my reflection and she said 'nah.'",
        "I read a tweet that said 'cancel your plans' and I obeyed.",
        "I think I saw a ghost and now I'm spooked.",
        "I need to prioritize overthinking tonight.",
        "I've decided to soft quit life for 12 hours.",
        "I'm being held hostage by comfort.",
        "I have a date with existential dread.",
        "I need to align with my higher self. She's antisocial.",
        "I'm in a monogamous relationship with isolation.",
        "I'm riding a wave of anxiety and can't get off.",
        "I already cancelled in my head. This is the formal part.",
        "I started a nap and now I'm too deep.",
        "I can't. But not in a dramatic way. Just... no.",
        "I just wanted to cancel something. This felt right."
    ]
    
    static func randomExcuse() -> String {
        funnyExcuses.randomElement() ?? "I just can't today."
    }
} 